pipeline {
    agent any
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"
            }
        }
        stage('Unit Test') {
            steps {
                echo "jakieś echo"
            }
        }
        stage('Smoke Test') {
            steps {
                echo "echo w testach"
            }
        }
    }
}